name: deploy to github pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up mdbook (v0.5.2)
        run: |
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.5.2/mdbook-v0.5.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          chmod +x mdbook
          mv mdbook ~/.cargo/bin/mdbook

      - name: Install mdbook-gitinfo (latest)
        run: |
          curl -fsSLO https://github.com/CompEng0001/mdbook-gitinfo/releases/latest/download/mdbook-gitinfo-linux.tar.gz
          tar -xzf mdbook-gitinfo-linux.tar.gz
          mv mdbook-gitinfo-linux ~/.cargo/bin/mdbook-gitinfo

      - name: Show mdbook version
        run: mdbook --version
      - name: Show gitinfo version
        run: mdbook-gitinfo --version

      - run: mdbook build examples

      - name: Deploy to github pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: examples/book
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
